### ISSUE TITLE
Error 500 when deleting user

### ISSUE THREAD

**Issue by TheElectronWill** [paulmillr/ostio-api#8]
I'm trying the ost.io API with the curl command. When I try to delete my account,  I get an error 500.

> `> curl -X DELETE http://api.ost.io/v1/users/TheElectronWill?access_token=<my token>`
> `<html><body><h1>500 Internal Server Error</h1>If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.</body></html>`

The access token is valid (got it with the API), because when I enter an other (invalid) one I get 
> "{"error":"Not authorized"}"

**Comment by paulmillr** [comment]
there is no such endpoint for right now even though it's in docs.

**Comment by TheElectronWill** [comment]
Okey, that explains everything :)
Shouldn't it be removed from the docs then?

**Comment by paulmillr** [comment]
yep

**Comment by TheElectronWill** [comment]
I think I can close this issue now. Thank you!
